<a href="https://colab.research.google.com/github/supernovaBvS/AWS-AI-ML-scholarship/blob/main/AI_Week7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# A - WORLD FOOD FACT

# B - Alcohol Consumption

In [2]:
import pandas as pd
drinks = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv')
drinks

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF
...,...,...,...,...,...,...
188,Venezuela,333,100,3,7.7,SA
189,Vietnam,111,2,1,2.0,AS
190,Yemen,6,0,0,0.1,AS
191,Zambia,32,19,4,2.5,AF
192,Zimbabwe,64,18,4,4.7,AF

In [3]:
drinks.groupby('continent')['beer_servings'].max()

continent
AF    376
AS    247
EU    361
OC    306
SA    333
Name: beer_servings, dtype: int64

In [4]:
# STEP 1 - Which continent drinks more beer on average?

drinks.groupby('continent')['beer_servings'].max()

continent
AF    376
AS    247
EU    361
OC    306
SA    333
Name: beer_servings, dtype: int64

In [ ]:
# STEP 2 - For each continent print the statistics for wine consumption.

In [ ]:
# STEP 3 -  Print the mean alcohol consumption per continent for every column

In [ ]:
# STEP 4 -  Print the median alcohol consumption per continent for every column

In [ ]:
# STEP 5 -  Print the mean, min and max values for spirit consumption.

# C - Euro 2012

In [ ]:
euro12 = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/02_Filtering_%26_Sorting/Euro12/Euro_2012_stats_TEAM.csv', sep=',')
euro12

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

In [ ]:
# Step 1 - Select only the Goal column.

In [ ]:
# Step 2 - How many team participated in the Euro2012?

In [ ]:
# Step 3 - What is the number of columns in the dataset?

In [ ]:
# Step 4 - View only the columns Team, Yellow Cards and Red Cards and assign them to a dataframe called discipline

In [ ]:
# Step 5 - Sort the teams by Red Cards, then to Yellow Cards

In [ ]:
# Step 6 - Calculate the mean Yellow Cards given per Team

In [ ]:
# Step 7 - Filter teams that scored more than 6 goals

In [ ]:
# Step 8 - Select the teams that start with G

In [ ]:
# Step 9 - Select the first 7 columns

In [ ]:
# Step 10 -  Select all columns except the last 3.

In [ ]:
# Step 11 - Present only the Shooting Accuracy from England, Italy and Russia